// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxcilcbpfdfkusrihnmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4Y2lsY2JwZmRma3Vzcmlobm1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2OTM4NzQsImV4cCI6MjA2NzI2OTg3NH0.VM2h1gkKXt-Z3bEZP_aJUFWKtcsj0C0vHpFalNzRwNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});